### ISSUE TITLE
Setup Python 3.10 as default and deprecate 3.8

### ISSUE THREAD

**Issue by Tansito** [Qiskit/qiskit-serverless#1251]
### What is the expected enhancement?

Taking account last messages from #484 I think it would be nice to start to prepare the project to remove Python 3.8 support and run our images with Python 3.10 by default (right now we are building them with 3.9).

We would need to continue taking a look to Python 3.11 but not a priority I would say.

**Comment by psschwei** [comment]
I think the two PRs above cover all we need here

**Comment by psschwei** [comment]
This was done in https://github.com/Qiskit/qiskit-serverless/releases/tag/v0.10.0
