### ISSUE TITLE
Broken links on README

### ISSUE THREAD

**Issue by jenglick** [Qiskit/qiskit-serverless#1363]
The 5 links to docs at end of [this section](https://github.com/Qiskit/qiskit-serverless?tab=readme-ov-file#quickstart) are broken and need to be updated to the new location: https://qiskit.github.io/qiskit-serverless/.

**Comment by akihikokuroda** [comment]
Thanks for this issue.  This PR #1362 has fix for them.

**Comment by Tansito** [comment]
From what I saw this issue is fixed so I proceed to close it, thank you!
