### ISSUE TITLE
CI: kuberenetes tests keep falling

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/qiskit-serverless#1369]
### Steps to reproduce the problem

https://github.com/Qiskit/qiskit-serverless/actions/runs/9485617392/job/26137977739?pr=1368
https://github.com/Qiskit/qiskit-serverless/actions/runs/9484713375/job/26134855753?pr=1366
https://github.com/Qiskit/qiskit-serverless/actions/runs/9485422545/job/26137478335?pr=1358

### What is the current behavior?

K8s tests keeps failing in #1368 #1366 #1358

### What is the expected behavior?

Tests should be running fine

**Comment by psschwei** [comment]
Fixes in #1366 #1373

**Comment by psschwei** [comment]
Fixes merged
