### ISSUE TITLE
Requesting more resources that you can have

### ISSUE THREAD

**Issue by Tansito** [Qiskit/qiskit-serverless#1379]
### Steps to reproduce the problem

When you request more resources that the cluster has available for you, you remain waiting for those resources. The problem is that if you ask for more resources that you can assign to your node you remain waiting for them indefinitely.

### What is the current behavior?

Create a parallel task with more cpus that you can assign to your node using the limites setup in the the `values.yaml`. The function remains in RUNNING state indefinitely.

### What is the expected behavior?

The job should be marked as FAILED with the error.

**Comment by psschwei** [comment]
So as of now we're not tracking the resource requests in the gateway, just the number of concurrent jobs that have been submitted. So we don't currently have a way to catch this. I think what we'd have to do is start storing this info in the JobConfig model. 

However, that may be a little tricky as the only way to currently set cpu / memory requirements are via the `distribute_task` function, which calls `ray.remote` from the client and as a result isn't connected to the gateway (in other words, it doesn't know anything about available resources).

There also doesn't appear to be a way to fail a job in Ray if there are insufficient resources... the job just queues indefinitely assuming resources will eventually become available. 

So this may not be an easy fix...

**Comment by Tansito** [comment]
Yeah, I was thinking in a solution for this but I didn't find anything either. A bit tricky 😅
