### ISSUE TITLE
Docker option in local is not working in Mac M1 chip

### ISSUE THREAD

**Issue by pacomf** [Qiskit/qiskit-serverless#365]
I try to run the mantra:

```
docker-compose pull
docker-compose up
```

in local with a Mac M1 Max chip and it is not working properly, because some images are not ready to run on this chip (gateway, ray-head,  qs-jupyter).

The main problem is about gateway, all requests are generating 500 errors.:S, maybe it is produced by ray dependency:

https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support

**Comment by akihikokuroda** [comment]
I think we can close this now.

**Comment by akihikokuroda** [comment]
@garrison Thanks for your comment.  We can build all containers for M1 now.  We have to have the place put the multi-arch images to resolve issue completely.

**Comment by psschwei** [comment]
> set `platform: linux/amd64` in `docker-compose.yml`

I know this ship has probably already sailed, but this ^^^ would get my vote to keep us all working off the same images...

**Comment by Tansito** [comment]
I totally open to review other options @psschwei if it works and simplifies the configuration you sell it to me 😂

**Comment by pacomf** [comment]
any update on it @psschwei ?

**Comment by psschwei** [comment]
> I totally open to review other options @psschwei if it works and simplifies the configuration you sell it to me joy

Two main thoughts here on pinning the platform to x86 / amd64:

* I think most places we'd install this for production will be x86 systems (ignoring laptops for this discussion), so there's not a major need for an arm64 image at this time
* it keeps everyone working on the same image (less chance to introduce bugs, or at least a better chance of them getting caught)

Corollary to everyone using the same image is there's less code to maintain. 

Not being a Mac user, I didn't know the M1s had an x86 emulator... :themoreyouknow:

> any update on it @psschwei ?

Aki's done a few PRs that I think have it mostly working on arm64.

I'll send a PR to set the platform to x86 and we can test that out too.
