### ISSUE TITLE
Add explicit support for Python 3.11

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit-serverless#484]
### What is the expected enhancement?

- [ ] Add Python 3.11 to list of Trove classifiers in `client/setup.py`
- [ ] Add 3.11 to list of supported Python versions in badge in `README.md`
- [ ] Add 3.11 to list of supported Python versions in badge in `client/README.md`
- [ ] Enable testing on Python 3.11 in CI (?)
- [ ] Confirm installation works on Windows (xref #1078)

**Comment by psschwei** [comment]
Ray doesn't have a Python 3.11 image just yet, so had to revert this in #560 ... will revert the revert (?) once the support is there

**Comment by psschwei** [comment]
Now that we've updated Ray to v2.6.2 in #867 we can revisit adding python 3.11 support as those images now exist at https://hub.docker.com/r/rayproject/ray/tags?page=1&name=2.6.2-py311

**Comment by akihikokuroda** [comment]
@psschwei Can we assign this to the future milestone not to forget?

**Comment by psschwei** [comment]
It's hard to say what milestone (unless we have a backlog one?), since Ray doesn't have a date for when they'll move out of experimental.... probably best to just drop the milestone for now and revisit if/when it gets there in Ray.

**Comment by psschwei** [comment]
As of Ray 2.9.0, Python 3.11 support is still experimental...
https://github.com/ray-project/ray/blob/8919bf0d1f12b6fbf515b6364c873544cf0ca25b/doc/source/ray-overview/installation.rst?plain=1#L103

**Comment by psschwei** [comment]
Hit an async error when running a quantum-serverless job using Python 3.11, so this one still isn't ready for prime time

**Comment by Tansito** [comment]
Last news from python version support:

https://github.com/ray-project/ray/issues/42343#issuecomment-1995969824

We can expect:
- python 3.8 deprecation for ray > 2.10 / 2.11
- end of march support for python 3.11? Not sure

**Comment by psschwei** [comment]
I think once we merge https://github.com/Qiskit/qiskit-serverless/pull/1272 we can add in Python 3.11 for the client

**Comment by Tansito** [comment]
I'm going to add this for June, thanks @psschwei 👍

**Comment by psschwei** [comment]
#1343 is the new one we need in order to support Python 3.11
