### ISSUE TITLE
Drop nightly support in favor of latest

### ISSUE THREAD

**Issue by Tansito** [Qiskit/qiskit-serverless#621]
### What is the expected enhancement?

From @psschwei comment : https://github.com/Qiskit-Extensions/quantum-serverless/pull/513#issuecomment-1548818823

Now that we are creating `latest` images we can discuss if we can drop support for `nightly`.

From my point of view I found the comment interesting and I would drop support for `nightly` just to not support more tags. What do you think @IceKhan13 , @akihikokuroda , @psschwei ?

**Comment by IceKhan13** [comment]
+1, let's drop nightly
