### ISSUE TITLE
Gateway: add runtime metadata to Jobs

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/qiskit-serverless#851]
### What is the expected enhancement?

Multiple users requested for simple metadata about jobs, like runtime. 

We can add signal to `Job` model to report `runtime` when job is finished.

**Comment by caleb-johnson** [comment]
What exact runtime do we want to measure here? I'm trying to understand where best to measure the time

**Comment by psschwei** [comment]
Do we have a list of the fields we'd want to add?
